---
- name: Install NGINX
  hosts: myNodes
  become: no
  gather_facts: false

  tasks:
    - name: Install the EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install the latest version of NGINX
      package:
        name: nginx
        state: latest

    - name: Copy index.html
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Activate NGINX service 
      service:
        name: nginx
        state: started
        enabled: yes
