version: "3"
services:
  centos-build-test:
    image: centos-ssh
    container_name: centos_build_test
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8082:8082"
    tmpfs:
      - /run
      - /tmp
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.2
    volumes:
      - /var/lib/docker/volumes/centos_build_test_home/_data:/var/centos_build_test_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always

  centos-preprod:
    image: centos-ssh
    container_name: centos_preprod
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8083:8083"
    tmpfs:
      - /run
      - /tmp
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.3
    volumes:
      - /var/lib/docker/volumes/centos_preprod_home/_data:/var/centos_preprod_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always
  
  centos-prod:
    image: centos-ssh
    container_name: centos_prod
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - "8084:8084"
    tmpfs:
      - /run
      - /tmp
    networks:
      orchestrationNetwork:
        ipv4_address: 192.168.10.4
    volumes:
      - /var/lib/docker/volumes/centos_prod_home/_data:/var/centos_prod_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: always

networks:
  orchestrationNetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.10.0/24
         gateway : 192.168.10.1
